### ISSUE TITLE
Ideas dump

### ISSUE THREAD

**Issue by nikevelik** [nikevelik/oct2024-ai#1]
# Спам на идеи 
*дотук от чата (от мен)*

Може (GameAI) да направим някакъв ProceduralContentGeneration, примерно някаква игра с пъзели. Примерно нещо такова: https://haztech-games.itch.io/procedural-sokoban-puzzle-generator

<img src="https://github.com/user-attachments/assets/4d88d483-dc7c-403d-ad3e-bb417125110d" alt="image description" width="300" />

- blockchain ai voting web app idea
- АI framework for smart contracts development, който да открива дупки в сигурността

**Comment by lunaticomic-vc** [comment]
https://www.linkedin.com/posts/audrey-chen-tech_hackathon-hackprinceton-vibewire-activity-7194476701966352386-sSun?utm_source=share&utm_medium=member_ios

**Comment by nikevelik** [comment]
<img src="https://github.com/user-attachments/assets/a779410f-88e7-48f2-8f24-701428fbfefb" alt="First image" width="300" />
<img src="https://github.com/user-attachments/assets/10eabdde-7f28-4b38-b372-9164536614ff" alt="Second image" width="300" />

**Comment by lunaticomic-vc** [comment]
https://devpost.com/software/redhat-panda

**Comment by lunaticomic-vc** [comment]
https://devpost.com/software/tunetok

**Comment by lunaticomic-vc** [comment]
https://www.linkedin.com/posts/bill-zhang1_linguify-main-activity-7242910420875796480-gYn4?utm_source=share&utm_medium=member_ios

**Comment by lunaticomic-vc** [comment]
https://www.linkedin.com/posts/riancorcino_computerscience-softwareengineer-hackathon-activity-7201235798011121665-PPOX?utm_source=share&utm_medium=member_ios
